openapi: 3.0.3
info:
  description: Play API
  title: Play API
  version: 1.0.0
servers:
- url: /
paths:
  /liveliness:
    get:
      operationId: getLiveliness
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getLiveliness_200_response"
          description: Service is alive
      summary: Check if the service is alive
      x-accepts:
      - application/json
  /proxy:
    post:
      operationId: postProxy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postProxy_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postProxy_200_response"
          description: Proxy request successful
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postProxy_400_response"
          description: Bad request
      summary: Proxy requests to another service
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    postProxy_400_response:
      example:
        error: Invalid request
      properties:
        error:
          example: Invalid request
          type: string
      type: object
    postProxy_request:
      properties:
        url:
          example: https://example.com
          type: string
        payload:
          example:
            key: value
          type: object
      type: object
    postProxy_200_response:
      example:
        response:
          key: value
      properties:
        response:
          example:
            key: value
          type: object
      type: object
    getLiveliness_200_response:
      example:
        status: alive
      properties:
        status:
          example: alive
          type: string
      type: object
