/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.LivelinessResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-28T00:33:30.840920-04:00[America/New_York]", comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "Health", description = "Health check endpoints")
public interface LivelinessApi {

    /**
     * GET /liveliness : Check if the service is alive
     * Useful for load balancers or monitoring tools.
     *
     * @return Service is alive (status code 200)
     */
    @Operation(
        operationId = "getLiveliness",
        summary = "Check if the service is alive",
        description = "Useful for load balancers or monitoring tools.",
        tags = { "Health" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Service is alive", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LivelinessResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/liveliness",
        produces = { "application/json" }
    )
    
    ResponseEntity<LivelinessResponse> _getLiveliness(
        
    );

}
