/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.GetLiveliness200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-26T19:35:46.310079470-04:00[America/New_York]", comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "liveliness", description = "the liveliness API")
public interface LivelinessApi {

    default LivelinessApiDelegate getDelegate() {
        return new LivelinessApiDelegate() {};
    }

    /**
     * GET /liveliness : Check if the service is alive
     *
     * @return Service is alive (status code 200)
     */
    @Operation(
        operationId = "getLiveliness",
        summary = "Check if the service is alive",
        responses = {
            @ApiResponse(responseCode = "200", description = "Service is alive", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetLiveliness200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/liveliness",
        produces = { "application/json" }
    )
    
    default ResponseEntity<GetLiveliness200Response> getLiveliness(
        
    ) {
        return getDelegate().getLiveliness();
    }

}
